import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  classesContainer: {
    backgroundColor: "white",
    marginTop: 10,
    width: "100%",
    borderRadius: 6,
    borderWidth: 2.2,
    borderColor: "#036363",
    padding: 10,
  },
  heading: {
    color: "#036363",
    alignSelf: "flex-start",
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 5,
    marginBottom: 10,
  },
  dataContainer: {
    width: "100%",
    borderWidth: 1,
    borderRadius: 2,
    borderColor: "#e0e0e0",
    borderBottomWidth: 0,
    shadowColor: "#e0e0e0",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 10,
  },
  imageContainer: {
    borderTopEndRadius: 6,
    borderTopStartRadius: 6,
    backgroundColor: "white",
    marginTop: 10,
    flex: 1,
  },
  images: {
    marginTop: 30,
    marginBottom: 30,
    width: 140,
    height: 140,
  },
  centeredContainer: {
    borderBottomEndRadius: 6,
    borderBottomStartRadius: 6,
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-evenly",
  },
  text: {
    fontSize: 24,
  },
  numberTxt: {
    fontSize: 24,
    color: "red",
  },
  socialContainerTxt: {
    borderTopEndRadius: 6,
    borderTopStartRadius: 6,
    marginTop: 10,
    backgroundColor: "white",
    alignItems: "center",
    paddingTop: 10,
  },
  socialContainer: {
    borderBottomEndRadius: 6,
    borderBottomStartRadius: 6,
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "space-evenly",
    flex: 1,
    paddingTop: 20,
    paddingBottom: 20,
  },
  socialIcons: {
    width: 55,
    height: 55,
  },
  teacherContainer: {
    backgroundColor: "#00000080",
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  teacherBlock: {
    backgroundColor: "white",
    marginTop: 10,
    width: "97%",
    borderRadius: 6,
    borderWidth: 2.2,
    borderColor: "#ed093f",
    padding: 10,
    marginBottom: 15,
  },
  teacherFullName: {
    color: "#3c2a75",
    alignSelf: "flex-start",
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 5,
    marginBottom: 10,
  },
  teacherContentTxt: {
    fontWeight: "bold",
    color: "#555457",
    fontSize: 16,
  },
});

export default styles;
